// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoUQvAXiu20_xv8-KZ6B1ZqbOX06RxhG0',
    appId: '1:31249981661:web:72d36902169781a4a33b34',
    messagingSenderId: '31249981661',
    projectId: 'todo-app-83eb9',
    authDomain: 'todo-app-83eb9.firebaseapp.com',
    databaseURL: 'https://todo-app-83eb9.firebaseio.com',
    storageBucket: 'todo-app-83eb9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBjeH6Kt1T9Swy2qf92BlQIkKYMTzILXg',
    appId: '1:31249981661:android:201381236069957ea33b34',
    messagingSenderId: '31249981661',
    projectId: 'todo-app-83eb9',
    databaseURL: 'https://todo-app-83eb9.firebaseio.com',
    storageBucket: 'todo-app-83eb9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNjad7HYTzVUG5x_qKHvmhmjb-U92R5MM',
    appId: '1:31249981661:ios:816b2f8817b73c56a33b34',
    messagingSenderId: '31249981661',
    projectId: 'todo-app-83eb9',
    databaseURL: 'https://todo-app-83eb9.firebaseio.com',
    storageBucket: 'todo-app-83eb9.appspot.com',
    androidClientId: '31249981661-ise0khais30p95hpv056ngfdn0h6urf8.apps.googleusercontent.com',
    iosClientId: '31249981661-0c9alh5hamojhts6bkjdfjp29hkm4vrl.apps.googleusercontent.com',
    iosBundleId: 'com.mmartinezdev.firebaseTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNjad7HYTzVUG5x_qKHvmhmjb-U92R5MM',
    appId: '1:31249981661:ios:15ddab13e84f5be2a33b34',
    messagingSenderId: '31249981661',
    projectId: 'todo-app-83eb9',
    databaseURL: 'https://todo-app-83eb9.firebaseio.com',
    storageBucket: 'todo-app-83eb9.appspot.com',
    androidClientId: '31249981661-ise0khais30p95hpv056ngfdn0h6urf8.apps.googleusercontent.com',
    iosClientId: '31249981661-30182e6iv17ad68nbc3mg10kvso8ls8p.apps.googleusercontent.com',
    iosBundleId: 'com.mmartinezdev.firebaseTest.RunnerTests',
  );
}
